# SPDX-FileCopyrightText: 2009 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.901004");
  script_version("2023-07-21T05:05:22+0000");
  script_tag(name:"last_modification", value:"2023-07-21 05:05:22 +0000 (Fri, 21 Jul 2023)");
  script_tag(name:"creation_date", value:"2009-08-27 13:43:20 +0200 (Thu, 27 Aug 2009)");
  script_tag(name:"cvss_base", value:"7.5");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:P/I:P/A:P");
  script_cve_id("CVE-2008-7047", "CVE-2008-7049");
  script_name("NatterChat Security Bypass Vulnerability");
  script_xref(name:"URL", value:"http://www.milw0rm.com/exploits/7172");
  script_xref(name:"URL", value:"http://www.securityfocus.com/bid/32385");
  script_xref(name:"URL", value:"http://www.securityfocus.com/bid/32395");
  script_xref(name:"URL", value:"http://www.milw0rm.com/exploits/7179");
  script_xref(name:"URL", value:"http://xforce.iss.net/xforce/xfdb/46748");
  script_xref(name:"URL", value:"http://xforce.iss.net/xforce/xfdb/46764");

  script_tag(name:"qod_type", value:"remote_analysis");
  script_category(ACT_MIXED_ATTACK);
  script_copyright("Copyright (C) 2009 Greenbone AG");
  script_family("Web application abuses");
  script_dependencies("secpod_natterchat_detect.nasl");
  script_require_ports("Services/www", 80);
  script_mandatory_keys("natterchat/detected");

  script_tag(name:"impact", value:"Attackers can exploit this issue to view, add, modify or delete
  information in the back-end database or bypass security restrictions.");

  script_tag(name:"affected", value:"NatterChat version 1.1 on Windows.");

  script_tag(name:"insight", value:"- Vulnerability in the 'home.asp' script that fails to
  adequately secure access to administrative scripts.

  - Multiple SQL injection flaws in login.asp, which can be caused via the
  'txtUsername' parameter and 'txtPassword' parameter in a form generated by home.asp.");

  script_tag(name:"solution", value:"No known solution was made available for at least one year since the disclosure
  of this vulnerability. Likely none will be provided anymore. General solution options are to upgrade to a newer
  release, disable respective features, remove the product or replace the product by another one.");

  script_tag(name:"summary", value:"NatterChat is prone to a security bypass vulnerability.");

  script_tag(name:"solution_type", value:"WillNotFix");

  exit(0);
}

include("http_func.inc");
include("port_service_func.inc");
include("version_func.inc");

nchatPort = http_get_port(default:80);

nchatVer = get_kb_item("www/" + nchatPort + "/NatterChat");
nchatVer = eregmatch(pattern:"^(.+) under (/.*)$", string:nchatVer);

if((nchatVer[2] != NULL) && (!safe_checks()))
{
  sndReq = http_get(item:string(nchatVer[2], "/admin/home.asp"),
                    port:nchatPort);
  rcvRes = http_send_recv(port:nchatPort, data:sndReq);

  if("Natterchat Administration - Home" >< rcvRes)
  {
    security_message(nchatPort);
    exit(0);
  }
}

if(nchatVer[1] != NULL)
{
  if(version_is_equal(version:nchatVer[1], test_version:"1.1")){
    security_message(nchatPort);
  }
}
