# SPDX-FileCopyrightText: 2016 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

# it seems that it is not possible to add more than 2500 values to an
# array. Therefore only printers for the moment.
mac_prefixes = make_array(
                          "00:00:03","Xerox",
                          "00:00:04","Xerox",
                          "00:00:05","Xerox",
                          "00:00:06","Xerox",
                          "00:00:07","Xerox",
                          "00:00:08","Xerox",
                          "00:00:AA","Xerox",
                          "00:55:00","Xerox",
                          "08:00:37","Xerox",
                          "08:00:72","Xerox",
                          "1C:7D:22","Xerox",
                          "9C:93:4E","Xerox",
                          "00:00:85","Canon",
                          "00:02:20","Canon",
                          "00:0F:A0","Canon",
                          "00:1E:8F","Canon",
                          "00:30:C4","Canon",
                          "00:BB:C1","Canon",
                          "00:C0:85","Canon",
                          "18:0C:AC","Canon",
                          "2C:9E:FC","Canon",
                          "60:12:8B","Canon",
                          "84:BA:3B","Canon",
                          "88:87:17","Canon",
                          "D8:49:2F","Canon",
                          "F4:81:39","Canon",
                          "F8:0D:60","Canon",
                          "00:04:00","Lexmark",
                          "00:20:00","Lexmark",
                          "00:21:B7","Lexmark",
                          "00:14:60","Kyocera",
                          "00:17:C8","Kyocera",
                          "00:1F:BD","Kyocera",
                          "00:22:94","Kyocera",
                          "00:C0:EE","Kyocera",
                          "24:5F:DF","Kyocera",
                          "34:A8:43","Kyocera",
                          "6C:76:60","Kyocera",
                          "80:73:9F","Kyocera",
                          "C4:21:C8","Kyocera",
                          "A4:5D:36","HewlettP",
                          "30:CD:A7","Samsung"
);

