# SPDX-FileCopyrightText: 2013 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

if(description)
{
  script_xref(name:"URL", value:"https://www.redhat.com/archives/rhsa-announce/2013-February/msg00055.html");
  script_xref(name:"URL", value:"http://www.securityfocus.com/bid/52973");
  script_oid("1.3.6.1.4.1.25623.1.0.870928");
  script_version("2024-03-21T05:06:54+0000");
  script_tag(name:"last_modification", value:"2024-03-21 05:06:54 +0000 (Thu, 21 Mar 2024)");
  script_tag(name:"creation_date", value:"2013-02-22 10:02:03 +0530 (Fri, 22 Feb 2013)");
  script_cve_id("CVE-2012-1182");
  script_tag(name:"cvss_base", value:"10.0");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:C/I:C/A:C");
  script_xref(name:"RHSA", value:"2013:0515-02");
  script_name("RedHat Update for openchange RHSA-2013:0515-02");

  script_tag(name:"summary", value:"The remote host is missing an update for the 'openchange'
  package(s) announced via the referenced advisory.");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2013 Greenbone AG");
  script_family("Red Hat Local Security Checks");
  script_dependencies("gather-package-list.nasl");
  script_mandatory_keys("ssh/login/rhel", "ssh/login/rpms", re:"ssh/login/release=RHENT_6");
  script_tag(name:"affected", value:"openchange on Red Hat Enterprise Linux Desktop (v. 6),
  Red Hat Enterprise Linux Workstation (v. 6)");
  script_tag(name:"solution", value:"Please Install the Updated Packages.");
  script_tag(name:"insight", value:"The openchange packages provide libraries to access Microsoft Exchange
  servers using native protocols. Evolution-MAPI uses these libraries to
  integrate the Evolution PIM application with Microsoft Exchange servers.

  A flaw was found in the Samba suite's Perl-based DCE/RPC IDL (PIDL)
  compiler. As OpenChange uses code generated by PIDL, this could have
  resulted in buffer overflows in the way OpenChange handles RPC calls. With
  this update, the code has been generated with an updated version of PIDL to
  correct this issue. (CVE-2012-1182)

  The openchange packages have been upgraded to upstream version 1.0, which
  provides a number of bug fixes and enhancements over the previous version,
  including support for the rebased samba4 packages and several API changes.
  (BZ#767672, BZ#767678)

  This update also fixes the following bugs:

  * When the user tried to modify a meeting with one required attendee and
  himself as the organizer, a segmentation fault occurred in the memcpy()
  function. Consequently, the evolution-data-server application terminated
  unexpectedly with a segmentation fault. This bug has been fixed and
  evolution-data-server no longer crashes in the described scenario.
  (BZ#680061)

  * Prior to this update, OpenChange 1.0 was unable to send messages with
  a large message body or with extensive attachment. This was caused by minor
  issues in OpenChange's exchange.idl definitions. This bug has been fixed
  and OpenChange now sends extensive messages without complications.
  (BZ#870405)

  All users of openchange are advised to upgrade to these updated packages,
  which fix these issues and add these enhancements.");
  script_tag(name:"qod_type", value:"package");
  script_tag(name:"solution_type", value:"VendorFix");

  exit(0);
}

include("revisions-lib.inc");
include("pkg-lib-rpm.inc");

release = rpm_get_ssh_release();
if(!release) exit(0);

res = "";

if(release == "RHENT_6")
{

  if ((res = isrpmvuln(pkg:"evolution-mapi", rpm:"evolution-mapi~0.28.3~12.el6", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"evolution-mapi-debuginfo", rpm:"evolution-mapi-debuginfo~0.28.3~12.el6", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"openchange", rpm:"openchange~1.0~4.el6", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"openchange-debuginfo", rpm:"openchange-debuginfo~1.0~4.el6", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if (__pkg_match) exit(99);
  exit(0);
}
