# SPDX-FileCopyrightText: 2016 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

CPE = "cpe:/a:jenkins:jenkins";

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.808276");
  script_version("2023-07-20T05:05:17+0000");
  script_cve_id("CVE-2011-4344");
  script_tag(name:"cvss_base", value:"2.6");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:H/Au:N/C:N/I:P/A:N");
  script_tag(name:"last_modification", value:"2023-07-20 05:05:17 +0000 (Thu, 20 Jul 2023)");
  script_tag(name:"creation_date", value:"2016-08-04 13:00:06 +0530 (Thu, 04 Aug 2016)");

  script_name("Jenkins Winstone Servlet Cross Site Scripting Vulnerability (Nov 2011) - Windows");

  script_tag(name:"summary", value:"Jenkins is prone to a cross-site scripting vulnerability.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable version is present on the target host.");

  script_tag(name:"insight", value:"The flaw is due to an insufficient input
  validation error in 'winstone' servlet container that Jenkins runs in when
  running in standalone mode.");

  script_tag(name:"impact", value:"Successful exploitation will allow remote
  attackers to embed malicious JavaScript into pages generated by Jenkins.");

  script_tag(name:"affected", value:"Jenkins main line prior to 1.438, Jenkins LTS prior to 1.409.3.");

  script_tag(name:"solution", value:"Jenkins main line users should update to 1.438,
  Jenkins LTS users should update to 1.409.3.");

  script_tag(name:"solution_type", value:"VendorFix");

  script_tag(name:"qod_type", value:"remote_banner");

  script_xref(name:"URL", value:"https://jenkins.io/security/advisory/2011-11-08/");
  script_xref(name:"URL", value:"http://www.securityfocus.com/bid/52384");

  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2016 Greenbone AG");
  script_family("Web application abuses");
  script_dependencies("gb_jenkins_consolidation.nasl", "os_detection.nasl");
  script_mandatory_keys("jenkins/detected", "Host/runs_windows");

  exit(0);
}

include("host_details.inc");
include("version_func.inc");

if( ! port = get_app_port( cpe:CPE ) )
  exit( 0 );

if( ! infos = get_app_full( cpe:CPE, port:port, exit_no_version:TRUE ) )
  exit( 0 );

version = infos["version"];
location = infos["location"];
proto = infos["proto"];

if( get_kb_item( "jenkins/" + port + "/is_lts" ) ) {
  if( version_is_less( version:version, test_version:"1.409.3" ) ) {
    vuln = TRUE;
    fix = "1.409.3";
  }
} else {
  if( version_is_less( version:version, test_version:"1.438" ) ) {
    vuln = TRUE;
    fix = "1.438";
  }
}

if( vuln ) {
  report = report_fixed_ver( installed_version:version, fixed_version:fix, install_path:location );
  security_message( port:port, data:report, proto:proto );
  exit( 0 );
}

exit( 99 );
