# SPDX-FileCopyrightText: 2016 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.703627");
  script_cve_id("CVE-2016-1927", "CVE-2016-2039", "CVE-2016-2040", "CVE-2016-2041", "CVE-2016-2560", "CVE-2016-2561", "CVE-2016-5099", "CVE-2016-5701", "CVE-2016-5705", "CVE-2016-5706", "CVE-2016-5731", "CVE-2016-5733", "CVE-2016-5739");
  script_tag(name:"creation_date", value:"2016-08-02 05:28:14 +0000 (Tue, 02 Aug 2016)");
  script_version("2024-02-02T05:06:05+0000");
  script_tag(name:"last_modification", value:"2024-02-02 05:06:05 +0000 (Fri, 02 Feb 2024)");
  script_tag(name:"cvss_base", value:"5.0");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:P/I:N/A:N");
  script_tag(name:"severity_vector", value:"CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N");
  script_tag(name:"severity_origin", value:"NVD");
  script_tag(name:"severity_date", value:"2016-07-05 17:09:20 +0000 (Tue, 05 Jul 2016)");

  script_name("Debian: Security Advisory (DSA-3627-1)");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2016 Greenbone AG");
  script_family("Debian Local Security Checks");
  script_dependencies("gather-package-list.nasl");
  script_mandatory_keys("ssh/login/debian_linux", "ssh/login/packages", re:"ssh/login/release=DEB8");

  script_xref(name:"Advisory-ID", value:"DSA-3627-1");
  script_xref(name:"URL", value:"https://www.debian.org/security/2016/DSA-3627-1");
  script_xref(name:"URL", value:"https://security-tracker.debian.org/tracker/DSA-3627");

  script_tag(name:"summary", value:"The remote host is missing an update for the Debian 'phpmyadmin' package(s) announced via the DSA-3627-1 advisory.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable package version is present on the target host.");

  script_tag(name:"insight", value:"Several vulnerabilities have been fixed in phpMyAdmin, the web-based MySQL administration interface.

CVE-2016-1927

The suggestPassword function relied on a non-secure random number generator which makes it easier for remote attackers to guess generated passwords via a brute-force approach.

CVE-2016-2039

CSRF token values were generated by a non-secure random number generator, which allows remote attackers to bypass intended access restrictions by predicting a value.

CVE-2016-2040

Multiple cross-site scripting (XSS) vulnerabilities allow remote authenticated users to inject arbitrary web script or HTML.

CVE-2016-2041

phpMyAdmin does not use a constant-time algorithm for comparing CSRF tokens, which makes it easier for remote attackers to bypass intended access restrictions by measuring time differences.

CVE-2016-2560

Multiple cross-site scripting (XSS) vulnerabilities allow remote attackers to inject arbitrary web script or HTML.

CVE-2016-2561

Multiple cross-site scripting (XSS) vulnerabilities allow remote attackers to inject arbitrary web script or HTML.

CVE-2016-5099

Multiple cross-site scripting (XSS) vulnerabilities allow remote attackers to inject arbitrary web script or HTML.

CVE-2016-5701

For installations running on plain HTTP, phpMyAdmin allows remote attackers to conduct BBCode injection attacks against HTTP sessions via a crafted URI.

CVE-2016-5705

Multiple cross-site scripting (XSS) vulnerabilities allow remote attackers to inject arbitrary web script or HTML.

CVE-2016-5706

phpMyAdmin allows remote attackers to cause a denial of service (resource consumption) via a large array in the scripts parameter.

CVE-2016-5731

A cross-site scripting (XSS) vulnerability allows remote attackers to inject arbitrary web script or HTML.

CVE-2016-5733

Multiple cross-site scripting (XSS) vulnerabilities allow remote attackers to inject arbitrary web script or HTML.

CVE-2016-5739

A specially crafted Transformation could leak information which a remote attacker could use to perform cross site request forgeries.

For the stable distribution (jessie), these problems have been fixed in version 4:4.2.12-2+deb8u2.

For the unstable distribution (sid), these problems have been fixed in version 4:4.6.3-1.

We recommend that you upgrade your phpmyadmin packages.");

  script_tag(name:"affected", value:"'phpmyadmin' package(s) on Debian 8.");

  script_tag(name:"solution", value:"Please install the updated package(s).");

  script_tag(name:"solution_type", value:"VendorFix");
  script_tag(name:"qod_type", value:"package");

  exit(0);
}

include("revisions-lib.inc");
include("pkg-lib-deb.inc");

release = dpkg_get_ssh_release();
if(!release)
  exit(0);

res = "";
report = "";

if(release == "DEB8") {

  if(!isnull(res = isdpkgvuln(pkg:"phpmyadmin", ver:"4:4.2.12-2+deb8u2", rls:"DEB8"))) {
    report += res;
  }

  if(report != "") {
    security_message(data:report);
  } else if(__pkg_match) {
    exit(99);
  }
  exit(0);
}

exit(0);
